const CATEGORIES = {
    amusement_park: {label:"Amusement park",color:"#594AA1"},
    bakery: {label:"Bakery",color:"#8E7E69"},
    bank: {label:"Bank",color:"#557A85"},
    bar: {label:"Bar",color:"#BD3447"},
    beauty_salon: {label:"Beauty salon",color:"#B26A72"},
    cafe: {label:"Cafe",color:"#73432A"},
    doctor: {label:"Doctor",color:"#85EAFA"},
    florist: {label:"Florist",color:"#EE00EB"},
    gas_station: {label:"Gas station",color:"#6F763E"},
    gym: {label:"Gym",color:"#340951"},
    hair_care: {label:"Hair care",color:"#CE80E4"},
    library: {label:"Library",color:"#E0D27E"},
    movie_theater: {label:"Movie theater",color:"#907CAA"},
    museum: {label:"Museum",color:"#98B2A3"},
    night_club: {label:"Night club",color:"#6C3EC1"},
    park: {label:"Park",color:"#79d945"},
    square: {label:"Town square",color:"#647475"},
    pharmacy: {label:"Pharmacy",color:"#08fc31"},
    post_office: {label:"Post office",color:"#f5dc02"},
    restaurant: {label:"Restaurant",color:"#E78107"},
    shopping_mall: {label:"Shopping mall",color:"#A05990"},
    spa: {label:"Spa",color:"#C86351"},
    store: {label:"Store",color:"#4375EE"},
    supermarket: {label:"Supermarket",color:"#2C07FB"},
    zoo: {label:"Zoo",color:"#057A34"},
};

export default CATEGORIES;